# Generated by Django 5.1.7 on 2025-03-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        # sent_by_id ustunini qo'shish operatsiyasini o'chirib tashlaymiz
    ]
