# Generated by Django 4.2.10 on 2025-03-23 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcastmessage",
            options={
                "ordering": ["-sent_at"],
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar",
            },
        ),
        migrations.RenameField(
            model_name="broadcastmessage",
            old_name="created_at",
            new_name="sent_at",
        ),
        migrations.AddField(
            model_name="broadcastmessage",
            name="sent_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
