# Generated by Django 5.1.6 on 2025-03-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('crypto', 'Crypto'), ('payme', 'Payme'), ('click', 'Click')], max_length=10),
        ),
    ]
