# Generated by Django 5.1.7 on 2025-03-15 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_comment_and_more'),
        ('subscriptions', '0004_rename_end_date_subscription_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Kutilmoqda'), ('admin_approved', 'Admin tasdiqladi'), ('admin_declined', 'Admin rad etdi'), ('error', 'Xatolik')], default='pending_approval', max_length=20),
        ),
    ]
