# Generated by Django 5.1.7 on 2025-03-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payment_approved_at_and_more'),
        ('subscriptions', '0004_rename_end_date_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('uzcard', '💳 Uzcard'), ('humo', '💳 Humo'), ('visa', '💳 Visa'), ('mastercard', '💳 Mastercard')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
    ]
