# Generated by Django 5.1.7 on 2025-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_payment_transaction_id_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
