# Generated by Django 5.1.7 on 2025-03-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_screenshot'),
        ('users', '0005_user_temp_data_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='updated_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payments', to='users.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.user'),
        ),
    ]
