# Generated by Django 5.1.7 on 2025-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_payment_updated_admin_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='updated_admin',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('declined', 'Rad etildi'), ('error', 'Xatolik')], default='pending_approval', max_length=20),
        ),
    ]
