# Generated by Django 5.1.7 on 2025-03-14 23:05

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_subscribed_user_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=users.models.generate_uuid, max_length=36, unique=True),
        ),
    ]
