# Generated by Django 5.1.7 on 2025-03-18 23:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_user_id_e23e69_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_f3e681_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_created_cf865c_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=users.models.generate_uuid, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_user_id',
            field=models.FloatField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
