# Generated by Django 5.1.7 on 2025-03-15 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_temp_data_alter_user_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recipient_type', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('subscribed', "Faqat obuna bo'lganlar"), ('active', 'Faol foydalanuvchilar')], max_length=20)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'verbose_name': 'Yuborilgan xabar',
                'verbose_name_plural': 'Yuborilgan xabarlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
