# Generated by Django 5.1.7 on 2025-03-15 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='recipient_type',
            field=models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('subscribed', 'Faqat obunachilarga'), ('active', 'Faol foydalanuvchilarga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
