# Generated by Django 4.2.10 on 2025-03-29 15:09

import apps.subscriptions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_days", models.PositiveIntegerField()),
                ("description", models.TextField(default="Obuna rejasi")),
            ],
            options={
                "verbose_name": "Obuna rejasi",
                "verbose_name_plural": "Obuna rejalari",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("waiting_admin", "Admin tasdiqlashi kutilmoqda"),
                            ("active", "Aktiv"),
                            ("expired", "Muddati tugagan"),
                            ("cancelled", "Bekor qilingan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "end_date",
                    models.DateTimeField(
                        default=apps.subscriptions.models.get_default_end_date
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("uzcard", "Uzcard"),
                            ("humo", "Humo"),
                            ("visa", "Visa"),
                            ("mastercard", "MasterCard"),
                            ("crypto", "Cryptocurrency"),
                            ("other", "Boshqa"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="payment_screenshots/"
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Obuna",
                "verbose_name_plural": "Obunalar",
                "ordering": ["-created_at"],
            },
        ),
    ]
