# Generated by Django 5.1.7 on 2025-03-22 14:28

import apps.subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=apps.subscriptions.models.get_default_end_date),
        ),
    ]
