# Generated by Django 4.2.10 on 2025-03-30 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_paymentmethod_paymenttype_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_type",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payment_screenshot",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscriptions.paymentmethod",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
