# Generated by Django 4.2.10 on 2025-03-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_users", "Can view users"),
                    ("can_edit_users", "Can edit users"),
                    ("can_block_users", "Can block users"),
                    ("can_view_signals", "Can view signals"),
                    ("can_create_signals", "Can create signals"),
                    ("can_edit_signals", "Can edit signals"),
                    ("can_delete_signals", "Can delete signals"),
                    ("can_view_payments", "Can view payments"),
                    ("can_approve_payments", "Can approve payments"),
                    ("can_reject_payments", "Can reject payments"),
                    ("can_view_subscriptions", "Can view subscriptions"),
                    ("can_manage_subscriptions", "Can manage subscriptions"),
                    ("can_view_reviews", "Can view reviews"),
                    ("can_manage_reviews", "Can manage reviews"),
                    ("can_send_broadcasts", "Can send broadcast messages"),
                ],
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
            },
        ),
    ]
