"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-7h!cyyi@x*e_2+&8efckt_8^jjbq2ugszp6c@239+3&coqi1up')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '[::1]',  # IPv6 localhost
    'top-invest-webapp.vercel.app',
    '*'  # Development uchun
]

# Security setting


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',  # Birinchi bo'lishi kerak
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'jazzmin',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'django_filters',
    
    # Project apps
    'apps.users',  # Users app ikkinchi bo'lishi kerak
    'apps.instruments',
    'apps.payments',
    'apps.reviews',
    'apps.signals',
    'apps.subscriptions',
    'apps.invest_bot',
    'apps.dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Simplified static file serving
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Telegram Bot settings
BOT_TOKEN = os.getenv('BOT_TOKEN')
try:
    CHANNEL_ID = int(os.getenv('CHANNEL_ID', '0'))
except ValueError:
    raise ValueError("CHANNEL_ID must be a number")

WEB_APP_URL = os.getenv('WEB_APP_URL', 'https://top-invest-webapp.vercel.app')

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://top-invest-webapp.vercel.app'
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Accept',
    'Accept-Language',
    'Content-Type',
    'Authorization',
    'X-Requested-With',
    'X-CSRFToken',
]

CORS_EXPOSE_HEADERS = [
    'Content-Length',
    'Content-Type',
]

CORS_ALLOW_CREDENTIALS = True

# CORS preflight settings
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "Top Invest Admin",
    "site_header": "Top Invest",
    "site_brand": "Top Invest",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Admin paneliga xush kelibsiz",
    "copyright": "Top Invest Ltd",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
        {"name": "Support", "url": "https://t.me/topinvest_support", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://t.me/topinvest_support", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "users", "subscriptions", "payments", "signals"],
    "custom_links": {
        "users": [{
            "name": "Xabar yuborish", 
            "url": "admin:users_user_changelist", 
            "icon": "fas fa-comments",
        }]
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "users.user": "fas fa-user",
        "subscriptions.subscription": "fas fa-credit-card",
        "subscriptions.subscriptionplan": "fas fa-list-alt",
        "payments.payment": "fas fa-money-bill-wave",
        "signals.signal": "fas fa-chart-line",
        "instruments.instrument": "fas fa-chart-bar",
        "reviews.review": "fas fa-star",
        "dashboard.broadcastmessage": "fas fa-envelope",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Top Invest API',
    'DESCRIPTION': 'Top Invest platformasi uchun API dokumentatsiya',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # Kategoriyalarni tartiblaymiz
    'TAGS': [
        {'name': 'auth', 'description': 'Autentifikatsiya'},
        {'name': 'users', 'description': 'Foydalanuvchilar'},
        {'name': 'users-admin', 'description': 'Foydalanuvchilar (Admin)'},
        {'name': 'signals', 'description': 'Signallar'},
        {'name': 'signals-admin', 'description': 'Signallar (Admin)'},
        {'name': 'payments', 'description': 'To\'lovlar'},
        {'name': 'payments-admin', 'description': 'To\'lovlar (Admin)'},
        {'name': 'subscriptions', 'description': 'Obunalar'},
        {'name': 'subscriptions-admin', 'description': 'Obunalar (Admin)'},
        {'name': 'reviews', 'description': 'Sharhlar'},
        {'name': 'reviews-admin', 'description': 'Sharhlar (Admin)'},
    ],
    
    # Kategoriyalarni tartiblash
    'TAG_SORTER': lambda x: {
        'auth': 0,
        'users': 1,
        'users-admin': 2,
        'signals': 3,
        'signals-admin': 4,
        'payments': 5,
        'payments-admin': 6,
        'subscriptions': 7,
        'subscriptions-admin': 8,
        'reviews': 9,
        'reviews-admin': 10,
    }.get(x['name'], 11),
}

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 hafta
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
