# Generated by Django 5.1.7 on 2025-03-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='signal',
            name='instrument',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signal',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='take_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='target_position',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
