# Generated by Django 5.1.7 on 2025-03-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_remove_signal_admin_remove_signal_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
