# Generated by Django 5.1.7 on 2025-03-18 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_instrument_alter_signal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='reviewed_by',
            field=models.ManyToManyField(related_name='reviewed_signals', through='signals.SignalReview', to=settings.AUTH_USER_MODEL),
        ),
    ]
