# Generated by Django 5.1.7 on 2025-03-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_signal_reviewed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='reviewed_by',
        ),
    ]
