# Generated by Django 4.2.10 on 2025-03-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0001_initial"),
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signal",
            old_name="is_sent",
            new_name="is_posted",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="take_profit",
        ),
        migrations.AddField(
            model_name="signal",
            name="custom_instrument",
            field=models.CharField(
                blank=True,
                help_text="Instrument bazada bo'lmasa",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="signals/"),
        ),
        migrations.AddField(
            model_name="signal",
            name="risk_percentage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="signal",
            name="take_profits",
            field=models.TextField(
                blank=True, help_text="Take profit darajalari JSON formatida", null=True
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="entry_price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="signal",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="instruments.instrument",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="signal_type",
            field=models.CharField(
                blank=True,
                choices=[("BUY", "Buy"), ("SELL", "Sell")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="stop_loss",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
