# Generated by Django 4.2.10 on 2025-03-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signal",
            name="entry_price",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="stop_loss",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="take_profit",
        ),
        migrations.AddField(
            model_name="signal",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Yopilgan vaqt"
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="success_rate",
            field=models.FloatField(default=0, verbose_name="Muvaffaqiyat darajasi"),
        ),
        migrations.CreateModel(
            name="PricePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Kirish narxi"),
                            ("TP", "Take-profit"),
                            ("SL", "Stop-loss"),
                        ],
                        max_length=10,
                        verbose_name="Narx turi",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narx"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tartib raqami"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Izoh"
                    ),
                ),
                (
                    "is_reached",
                    models.BooleanField(default=False, verbose_name="Yetib borildimi"),
                ),
                (
                    "reached_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yetib borilgan vaqt"
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_points",
                        to="signals.signal",
                        verbose_name="Signal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Narx nuqtasi",
                "verbose_name_plural": "Narx nuqtalari",
                "ordering": ["order"],
            },
        ),
    ]
