# Generated by Django 4.2.10 on 2025-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0002_remove_signal_entry_price_remove_signal_stop_loss_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricepoint",
            name="price",
            field=models.CharField(max_length=50, verbose_name="Narx"),
        ),
    ]
