# Generated by Django 4.2.10 on 2025-03-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0003_alter_pricepoint_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signal",
            name="closed_at",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="success_rate",
        ),
        migrations.AddField(
            model_name="signal",
            name="entry_prices",
            field=models.JSONField(
                default=list,
                help_text='Kirish narxlari ro\'yxati. Masalan: ["1.2345", "1.2350"]',
                verbose_name="Kirish narxlari",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="leverage",
            field=models.IntegerField(
                blank=True,
                help_text="Tavsiya etilgan leverage",
                null=True,
                verbose_name="Leverage",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="risk_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Depozitdan risk qilinadigan foiz",
                max_digits=5,
                null=True,
                verbose_name="Risk foizi",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="stop_losses",
            field=models.JSONField(
                default=list,
                help_text="Stop-loss narxlari ro'yxati",
                verbose_name="Stop-loss narxlari",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="take_profits",
            field=models.JSONField(
                default=list,
                help_text="Take-profit narxlari ro'yxati",
                verbose_name="Take-profit narxlari",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="timeframe",
            field=models.CharField(
                blank=True,
                help_text="Signal timeframe'i (M5, M15, H1, H4, D1)",
                max_length=10,
                null=True,
                verbose_name="Timeframe",
            ),
        ),
    ]
